### PR TITLE
Add copyright symbol © to ‘About’ tab

### PR DESCRIPTION
**Pull request by rbazaud**

### CODE REVIEW

**Comment by palinek** [comment]
I personaly tend to avoid non ASCII7 chars in C++ sources as AFAIK the interpretation of them is compiler/environment specific. (maybe it's time for me to read something about this theme)

**Comment by jleclanche** [comment]
@palinek That seems silly, all the compilers we support should use utf8 now...

**Comment by palinek** [comment]
Just read some doc in Qt: ... http://doc.qt.io/qt-5/qobject-obsolete.html#trUtf8 

They also advise to use escape sequencies...

**Comment by paulolieuthier** [comment]
I agree with @palinek. All source code must be pure ASCII.

**Comment by rbazaud** [comment]
Yes, I've never seen a compiler reject a file for being in UTF-8 encoding… ASCII was kind of a common denominator, a long time ago. Moreover it's in a string, not in a variable name, there were a few advantages to “pure ASCII” they tend to become less and less valid especially in an i8n context…

**Comment by jleclanche** [comment]
@rbazaud @paulolieuthier @palinek I'm landing this, double-checked with someone who knows compilers a lot better than I do that it was safe to do so. If it causes issues please report back, we'll revert, it'll make for a case study. :)

**Comment by jleclanche** [comment]
Landed in 731bc5a.

**Comment by paulolieuthier** [comment]
It won't cause issues, it was just for the sake of standardization. But anyway, @rbazaud is right.

**Comment by rbazaud** [comment]
thanks everyone.

**Pull request closed without merging**
