### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by jleclanche** [comment]
@luis-pereira IMO you can land these sorts of PRs without waiting for a GTM, just flag all the changes somewhere on the ML or on github.

gtm

**Comment by luis-pereira** [comment]
@jleclanche Hoping that someone else test it. I know.... I'm an believer.
Will merge probably in the beginning of next week. I will not be around, during the weekend.

**Comment by pmattern** [comment]
95ffcf4 from https://github.com/lxde/lxqt-about/tree/build-system compiles and works flawlessly on Arch Linux i686 and x86_64 here.

**Comment by paulolieuthier** [comment]
GTM. @luis-pereira you are a man of faith.

**Pull request merged**
