### PR TITLE
Show only in LXQt

### PR DESCRIPTION
**Pull request by agaida**
Use valid categories

### CODE REVIEW

**Comment by jleclanche** [comment]
@agaida I just wouldn't put it in settings at all. If you remove that, you can land it.

**Comment by pmattern** [comment]
Neither entry 'Qt' nor 'Documentation' as stated in line "Categories" is considered by recent lxqt-applications.menu. So using these values LXQt about isn't considered at all in Applications menu by default.

**Comment by paulolieuthier** [comment]
@agaida please, rebase and squash.

**Comment by stefonarch** [comment]
No idea where to put it, "other" seems strange too. In top of the menu as single voice?
Somewhere related: clicking the links in about they do not open:
xdg-open: no method available for opening 'http://razor-qt.org'
xdg-open: no method available for opening 'http://lxqt.org'

I had a similar issue with darktable and xdg-email, made a dirty hack to make recognise lxqt as kde in the script. The problem lays in xdg which does not recognise lxqt.

**Comment by agaida** [comment]
@paulolieuthier - i would do so - but please, one should stand up and suggest a valid xdg category. The question remains - where want we show the about? The only two opinions right now are:
* Not in settings
* Not in other
:P

**Comment by pmattern** [comment]
@stefonarch 
Can't confirm the failure opening those websites here.
Primarily xdg-open considers file mimeapps.list in $XDG_CONFIG_DIRS and $XDG_CONFIG_HOME according to [MIME Applications Specification](http://www.freedesktop.org/wiki/Specifications/mime-apps-spec), environment variables covering paths according to [Base Directory Specification](http://www.freedesktop.org/wiki/Specifications/basedir-spec). If the file exists at none of those four locations, file mimeinfo.cache is used as fallback. The latter is actually just a cache summarizing the values of key MimeTypes in all desktop entry files (*.desktop) available but gets used as fallback to chose default applications to handle MIME types as well. All those settings can be queried by running `xdg-mime query default x-scheme-handler/http[s]`.
Also, if xdg-open detects that similar tools like gvfs-open or Xfce's exo-open are available it will use those as backend. Thus an eventual misconfiguration of one of those tools could be the reason for you findings, too.
So you may want to check whether there's something wrong regarding all that stuff on your system.

**Comment by stefonarch** [comment]
Thanks for all the indormation.
$xdg-mime query default x-scheme-handler/http gives me
qupzilla.desktop and at the moment it works again as it should, no idea
why it did not in that given moment.

But I think
$xdg-email
is not working well  without modifying the script to detect properly LXQt,
actually it should detect gnome, lxde, mate, kde and enlightment.
I had this problem time ago while trying sending pics exported directly from
darktable, got "no action available" (solved for me with xdg-email
detecting LXQt as Kde), while on another clean system I set up just now
it opens qupzilla... with thunderbird set to default application.



Il 24/05/2015 15:23, Peter Mattern ha scritto:

**Comment by paulolieuthier** [comment]
@agaida I'd put other. If not, in our LXQt settings submenu.

**Comment by pmattern** [comment]
Xfce is putting its counterpart in the top-level of the main menu. Just saying.

**Comment by paulolieuthier** [comment]
Top level is better, indeed.

**Comment by agaida** [comment]
ok - lets drop this for now, fix the license thing first.
@paulolieuthier - what is to be done to put this in Top level? I like the idea very  much.

**Comment by paulolieuthier** [comment]
@agaida I don`t know.

**Comment by stefonarch** [comment]
@agaida : for me works in the menu file adding:

http://pastebin.com/su0kTXzX
schermata03

**Comment by paulolieuthier** [comment]
@agaida what happened?

**Pull request closed without merging**
