### PR TITLE
Add simple README.md file

### PR DESCRIPTION
**Pull request by rbazaud**

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm

**Comment by jleclanche** [comment]
BTW, don't merge it from github, land it with git. I'll give you an alias for this on IRC.

**Comment by rbazaud** [comment]
Thanks, I replied on IRC, but I just missed you apparently. It's fortunate to have waited for the GTM then :smile:

**Comment by palinek** [comment]
@rbazaud The way you merged this PR is exactly that what is @jleclanche trying to avoid. We don't want to have merge commits in the history.

... I've forcepushed the merge commits out:
```
(11:18:50) GitHub: [lxqt-about] rbazaud pushed 3 new commits to master: https://github.com/lxde/lxqt-about/compare/df906c2884cf...1754aba953ec
(11:18:50) GitHub: lxqt-about/master a26f4cd Raphaël Bazaud: Add simple README.md file
(11:18:50) GitHub: lxqt-about/master 2a35818 Raphaël Bazaud: Merge pull request #20 from rbazaud/lxqt-about
(11:18:50) GitHub: lxqt-about/master 1754aba Raphaël Bazaud: Merge branch 'rbazaud-add-readme'
(11:23:46) GitHub: [lxqt-about] palinek force-pushed master from 1754aba to c6eb938: https://github.com/lxde/lxqt-about/commits/master
(11:23:46) GitHub: lxqt-about/master c6eb938 Raphaël Bazaud: Add simple README.md file
```

@jleclanche we probably should mention a note about prefered merging and log phrasing somewhere

**Comment by jleclanche** [comment]
@palinek Yeah I was just thinking about adding it to the doc, but I'm having hardware issues right now Im trying to fix. Can you take care of it?

**Comment by rbazaud** [comment]
I used command line, exactly the given command line

**Comment by rbazaud** [comment]
And I sent an email to jlelanche to ask about the 2nd merge…

**Comment by rbazaud** [comment]
but it was already too late…

**Comment by jleclanche** [comment]
@rbazaud Don't worry about it, I was gonna give you a proper alias for it.

**Comment by jleclanche** [comment]
`merge-pr = "!f() { git fetch $1 $2; git branch _FETCH_HEAD FETCH_HEAD && git rebase HEAD _FETCH_HEAD && git checkout master && git merge --ff-only _FETCH_HEAD; git branch -d _FETCH_HEAD; }; f"`

**Comment by rbazaud** [comment]
Ok, thanks !

**Comment by palinek** [comment]
> Yeah I was just thinking about adding it to the doc, but I'm having hardware issues right now Im trying to fix. Can you take care of it?

Not right now... maybe later today/tomorrow

**Comment by rbazaud** [comment]
@palinek some of us don't read minds :smile:

**Comment by jleclanche** [comment]
@rbazaud Can you stay on IRC please? It makes it a lot easier.

**Comment by palinek** [comment]
@rbazaud I didn't want to offend you. Just wanted to remove the merge commits quickly... as [chaging history in public repository is a bad thing](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Comment by rbazaud** [comment]
@jleclanche I will, after a reboot, had to kill my Quassel

@palinek no trouble, too much caffeine, not enough sleep, thank you for the educated answer.

**Pull request merged**
