### PR TITLE
Minor update of README.md

### PR DESCRIPTION
**Pull request by rbazaud**
Use of “curly quotes” (Unicode) instead of ASCII

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Why?

**Comment by rbazaud** [comment]
Mainly to train myself with «PR handling» so that I don't mess, like last time… :-/

**Comment by paulolieuthier** [comment]
That's great, you can count on me for help. But we must not insert unnecessary non-ASCII characters in our code.

**Comment by rbazaud** [comment]
That being said the README appears on the main page of the project, as minor as it is, every typographical advices stay true, see
* http://smartquotesforsmartpeople.com/
* http://practicaltypography.com/straight-and-curly-quotes.html

**Comment by rbazaud** [comment]
Tnaks. It's a `README` file, not code _stricto sensu_, and I wouldn't make «unnecessary changes» just to train myself, that would defeat the purpose IMO (see previous URL) :smile: don't you think ?

**Comment by paulolieuthier** [comment]
From the website you linked: 
```
Is it ever OK to use straight quotes?

When dealing with code, straight quotes are often required. Otherwise, straight quotes should never appear in your design work and professional writing, unless you are making a site about proper punctuation.
```

But you're right, it's not code (at least not code that will get to the users). You can merge this, although it's still smelling to me. :smile:

**Comment by rbazaud** [comment]
Thanks, done. If you cannot see them in your terminal, it's probably because you're using ASCII :wink: If you really want it, it is still «do-able» to submit another PR in order to revert the change… :octocat:

**Comment by palinek** [comment]
I don't think that any of public LXQt's repositories is good place to train PRs & merging them. Why aren't you trying such things in your own repository/fork?

**Comment by rbazaud** [comment]
As I said, it was «**mainly** to train myself», and trying with my repository was indeed my first attempt but as you would know you cannot fork a repository that belongs to you, unless you create a fake git account, and without a fork… which is why I use minor changes (not unnecessary IMO it is an improvement, like adding ©) on minor projects. Once again, a `README` file, in `lxqt-about`. FYI, the `README` file didn’t exist for a long time before. But maybe if I used ‘_learn_’ instead of ‘_train_’ would you be more understanding. If so please forgive my English.

**Pull request merged**
